---
title: "Uitvoeringsprotocol"
# format: html
format:
  docx:
    reference-doc: template_hhsk.docx
date: today
embed-resources: true
engine: knitr
params:
  project_naam: "TEST PROJECT"
  project_opdrachtgever: "HHSK"
  project_opdrachtnemer: "Aannemer ABC"
  project_wettelijk_belang: "Festival!"
  project_gebied: "Het gebied dat ik gekozen heb"
  project_activiteiten: ["Activiteit 1", "Activiteit 2"]
  uitvoering_start: "1999-01-01"
  uitvoering_eind: "1999-12-31"
  soorten_aanwezig: ["Soort 1", "Soort 2", "Soort 3"]
  soorten_habitat: ["Soort 1", "Soort 2", "Soort 3", "Soort 4"]
---

`r params$project_naam`

# Project

## Projectinformatie

Opdrachtgever: *`r params$project_opdrachtgever`*

Opdrachtnemer: *`r params$project_opdrachtnemer`*

Contract: ???

perceel: ???

specifieke locatie: ???

Wettelijk belang: *`r params$project_wettelijk_belang`*

## Gebied

Projectgebied: *`r params$project_gebied`*

**Eventueel hier een kaartje met het projectgebied**

## Periode werkzaamheden

Uitvoering van de werkzaamheden vindt plaats van *`r params$uitvoering_start`* tot *`r params$uitvoering_eind`*

## Activiteit(en)

*`r params$project_activiteiten[1]`*

*`r params$project_activiteiten[2]`*

Combinatie van activiteiten

*`r params$project_activiteiten`*

# Beschermde soorten



# Maatregelen

## Algemene maatregelen

**Invullen o.b.v. type activiteit**

## Soortspecifieke maatregel

**Invullen op basis van relevante soorten**

# Bijlage - Overzicht soorten
